# Generated by Django 5.1.7 on 2025-03-22 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('importance', models.CharField(choices=[('Important', 'Have to done quickly.'), ('Less Important', 'Can be done after some time.'), ('No Hurry', 'Can be done after more time just chill.')], max_length=20)),
                ('done_upto', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
