# Generated by Django 5.1.7 on 2025-03-22 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='done_upto',
            field=models.DateField(verbose_name=datetime.datetime(2025, 3, 22, 2, 20, 59, 455181, tzinfo=datetime.timezone.utc)),
        ),
    ]
